Controllers/AppLogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SUMBER.Data;
using SUMBER.Models.Modules;

namespace SUMBER.Controllers
{
    [Authorize(Roles = "SuperAdmin,Admin")]
    public class AppLogController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public AppLogController(ApplicationDbContext context,
            UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: AppLog
        public async Task<IActionResult> Index(
            string searchUsername,
            string searchModulFrom,
            string searchModulTo,
            string searchDateFrom,
            string searchDateTo)
        {
            var appLog = new List<AppLog>();

            if (!String.IsNullOrEmpty(searchUsername) ||
                !String.IsNullOrEmpty(searchModulFrom) ||
                !String.IsNullOrEmpty(searchModulTo) ||
                !String.IsNullOrEmpty(searchDateFrom) ||
                !String.IsNullOrEmpty(searchDateTo))
            {
                appLog = _context.AppLog.ToList();
            }

            //function search userList
            var userList = await _context.applicationUsers.Include(x=> x.SuPekerja).ToListAsync();

            List<SelectListItem> userSelect = new();
            userSelect.Add(new SelectListItem() { Text = "-- Pilih Pengguna --", Value = "" });
            foreach (var q in userList)
            {
                userSelect.Add(new SelectListItem() { Text = q.Nama + " (" + q.UserName + ")", Value = q.UserName });
            }

            if (!String.IsNullOrEmpty(searchUsername))
            {
                ViewBag.username = new SelectList(userSelect, "Value", "Text", searchUsername);
                appLog = appLog.Where(x => x.UserId == searchUsername).ToList();
            }
            else
            {
                ViewBag.username = new SelectList(userSelect, "Value", "Text", "");
            }
            //function search userList end

            //function search date
            if (!String.IsNullOrEmpty(searchDateFrom) && !String.IsNullOrEmpty(searchDateTo))
            {
                DateTime date1 = DateTime.Parse(searchDateFrom);
                DateTime date2 = DateTime.Parse(searchDateTo);

                appLog = appLog.Where(x => x.LgDate >= date1 && x.LgDate <= date2).ToList();

                ViewData["DateFrom"] = searchDateFrom;
                ViewData["DateTo"] = searchDateTo;
                //akAkaun = akAkaun.OrderByDescending(c => c.Tarikh.Date).ThenBy(c => c.Tarikh.TimeOfDay);

            }
            //function search date end

            //function search modul range
            if (!String.IsNullOrEmpty(searchModulFrom) && !String.IsNullOrEmpty(searchModulTo))
            {
                Tuple<string, string> range = Tuple.Create(searchModulFrom, searchModulTo);
                appLog = appLog.Where(s =>
                        range.Item1.CompareTo(s.LgModule.Substring(0, range.Item1.Length)) <= 0 &&
                        s.LgModule.Substring(0, range.Item2.Length).CompareTo(range.Item2) <= 0)
                        .ToList();

                ViewData["ModulFrom"] = searchModulFrom;
                ViewData["ModulTo"] = searchModulTo;
            }
            // function search modul range end
            return View(appLog.OrderBy(b => b.LgDate).ThenBy(b => b.LgModule).ToList());
        }
   
    }
}

Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SUMBER.Data;
using SUMBER.Models.Login.ViewModel;
using SUMBER.Models.Modules;
using SUMBER.Models.Modules.IRepository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SUMBER.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly AppLogIRepository<AppLog, int> _appLog;

        public ProfileController(
            ApplicationDbContext db,
            UserManager<IdentityUser> userManager,
            AppLogIRepository<AppLog, int> appLog)
        {
            _db = db;
            _userManager = userManager;
            _appLog = appLog;
        }

        [HttpGet]
        public async Task<IActionResult> ChangePassword()
        {
            var user = await _db.applicationUsers.FirstOrDefaultAsync(x => x.UserName == User.Identity.Name);

            ResetPasswordViewModel viewModel = new ResetPasswordViewModel();

            viewModel.Email = user.Email;

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Supervisor,User")]
        public async Task<IActionResult> ChangePassword(ResetPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(model.Email);

                if (user != null)
                {
                    model.Code = await _userManager.GeneratePasswordResetTokenAsync(user);

                    var result = await _userManager.ResetPasswordAsync(user, model.Code, model.Password);
                    if (result.Succeeded)
                    {
                        TempData[SD.Success] = "Tukar Katalaluan berjaya..!";
                        return RedirectToAction(nameof(HomeController.Index), "Home");
                    }
                    AddErrors(result);
                }  

            }

            TempData[SD.Error] = "Tukar Katalaluan Gagal..!";
            return View(model);
        }
        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }
    }
}

Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SUMBER.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SUMBER.Controllers
{
    [Authorize(Roles = "SuperAdmin, Admin")]
    public class RolesController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public RolesController(ApplicationDbContext db, UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _db = db;
            _userManager = userManager;
            _roleManager = roleManager;
        }


        public IActionResult Index()
        {
            var roles = _db.Roles.ToList();
            return View(roles);
        }

        [HttpGet]
        public IActionResult Upsert(string id)
        {
            if(String.IsNullOrEmpty(id))
            {
                return View();
            }
            else
            {
                //update
                var objFromDb = _db.Roles.FirstOrDefault(u => u.Id == id);
                return View(objFromDb);
            }
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(IdentityRole roleObj)
        {
            if(await _roleManager.RoleExistsAsync(roleObj.Name))
            {
                //error
                TempData[SD.Error] = "Data telah wujud. Maklumat tidak disimpan.";
                return RedirectToAction(nameof(Upsert));
            }
            if(string.IsNullOrEmpty(roleObj.Id))
            {
                //create
                await _roleManager.CreateAsync(new IdentityRole() { Name = roleObj.Name });
                TempData[SD.Success] = "Maklumat berjaya disimpan.";
            }
            else
            {
                
                var objRoleFromDb = _db.Roles.FirstOrDefault(u => u.Id == roleObj.Id);
                if (objRoleFromDb ==null)
                {
                    TempData[SD.Error] = "Data tidak dijumpai.";
                    return RedirectToAction(nameof(Index));
                }
                objRoleFromDb.Name = roleObj.Name;
                objRoleFromDb.NormalizedName = roleObj.Name.ToUpper();
                var result = await _roleManager.UpdateAsync(objRoleFromDb);
                TempData[SD.Success] = "Maklumat berjaya diubah.";
            }
            return RedirectToAction(nameof(Index));

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(string id)
        {

            var objRoleFromDb = _db.Roles.FirstOrDefault(u => u.Id == id);
            var userRolesForThisRole = _db.UserRoles.Where(u => u.RoleId == id).Count();
            if (userRolesForThisRole > 0)
            {
                TempData[SD.Error] = "Data ini terkait dengan Pengguna. Operasi hapus tidak dibenarkan.";
                return RedirectToAction(nameof(Index));
            }
            await _roleManager.DeleteAsync(objRoleFromDb);
            TempData[SD.Success] = "Data berjaya dihapuskan..!";
            return RedirectToAction(nameof(Index));


        }
    }
}

Views/Shared/GlobalError.cshtml
@{
    ViewData["Title"] = "Penyelenggaraan Sistem";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}
<style>
    .wrap-login {
        padding: 42px 50px 33px 55px;
        background: #fff;
        border-radius: 10px;
        display: flex;
        flex-wrap: wrap;
        justify-content: space-evenly;
    }

    .login-pic {
        width: 100%;
    }
</style>
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login animate__bounceIn">
            <div class="login-pic text-center">
                <h3 class="text-danger mb-2">Sistem Mengalami Masalah Teknikal</h3>
                <h6 class="text-muted">Sila nyatakan isu yang timbul kepada pihak kami. Terima kasih.</h6>

            </div>
        </div>
    </div>
</div>

Views/Shared/HandleError.cshtml
@{
    ViewData["Title"] = ViewData["ErrorMessage"];

}

<div class="container">
    <div class="card jumbotron center ac-light" style="">
        <h1 class="text-danger ">@ViewData["ErrorMessage"] </h1>
        <h5 class="mb-3">Ralat berlaku. Sila kembali ke Halaman Utama.</h5>
        <div class="card-img-overlay text-right" style="overflow:hidden; opacity:20%;">
            <a class="btn-block " asp-controller="Home" asp-action="Index">
                <i class="fas fa-ban fa-10x" style="font-size:60vh;"></i>
            </a>
        </div>
        
        <a class="btn ac-info" asp-controller="Home" asp-action="Index">
            Kembali Ke Halaman Utama
        </a>
    </div>
</div>

Views/Shared/_DaftarPartialNavbar.cshtml
<li class="nav-item">
    <a class="nav-link collapsed text-truncate
    @Html.ActiveClass("SuPekerja") " href="#submenuDaftar" data-toggle="collapse" data-target="#submenuDaftar"><i class="fa fa-user-edit pr-2"></i><span class="pl-0">Daftar</span> </a>
    <div class="collapse" id="submenuDaftar" aria-expanded="false">
        <ul class="flex-column pl-2 nav">
            <li class="nav-item"><a class="nav-link py-1 ml-3 @Html.ActiveSideBarClass("SuPekerja")" asp-controller="SuPekerja" asp-action="Index"><span>Anggota</span></a></li>
        </ul>
    </div>
</li>

Views/Shared/_Favicons.cshtml
<link runat="server" rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link runat="server" rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link runat="server" rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link runat="server" rel="manifest" href="/site.webmanifest">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

Views/Shared/_JadualPartialNavbar.cshtml
<li class="nav-item">
    <a class="nav-link collapsed text-truncate
    @Html.ActiveClass("JBahagian") 
    @Html.ActiveClass("JKW")
    @Html.ActiveClass("AkBank") 
    @Html.ActiveClass("JBank")
    @Html.ActiveClass("JCaraBayar")
    @Html.ActiveClass("JAgama") 
    @Html.ActiveClass("JBangsa")
    @Html.ActiveClass("JSukan") 
    @Html.ActiveClass("JTahapAktiviti") 
    @Html.ActiveClass("JNegeri")
    @Html.ActiveClass("JSuTarafJawatan")
    @Html.ActiveClass("JSuGredGaji")
    @Html.ActiveClass("JSuKodGaji")
    @Html.ActiveClass("JSuPCB")
    @Html.ActiveClass("JSuKWSP") 
    
    
    " href="#submenuJadual" data-toggle="collapse" data-target="#submenuJadual"><i class="fas fa-columns pr-2
    "></i><span class="pl-1">Jadual</span></a>
    <div class="collapse" id="submenuJadual" aria-expanded="false">
        <ul class="flex-column pl-2 nav">

            <li class="nav-item">
                <a class="nav-link  text-truncate collapsed py-1 ml-3
                @Html.ActiveClass("JBahagian")
                @Html.ActiveClass("JKW")" href="#submenuJadualsub1" data-toggle="collapse" data-target="#submenuJadualsub1"><span>Belanjawan</span></a>
                <div class="collapse" id="submenuJadualsub1" aria-expanded="false">
                    <ul class="flex-column nav pl-4">
                        <li class="nav-item">
                            <a class="nav-link p-1 text-truncate pl-4 @Html.ActiveSideBarClass("JBahagian")" asp-area="" asp-controller="JBahagian" asp-action="Index">
                                Bahagian
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link p-1 text-truncate pl-4 @Html.ActiveSideBarClass("JKW")" asp-area="" asp-controller="JKW" asp-action="Index">
                                Kumpulan Wang
                            </a>
                        </li>
                    </ul>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link  text-truncate collapsed py-1 ml-3
                @Html.ActiveClass("JBank")" href="#submenuJadualsub2" data-toggle="collapse" data-target="#submenuJadualsub2"><span>Pembayaran / Penerimaan</span></a>
                <div class="collapse" id="submenuJadualsub2" aria-expanded="false">
                    <ul class="flex-column nav pl-4">
                        <li class="nav-item">
                            <a class="nav-link p-1 text-truncate pl-4 @Html.ActiveSideBarClass("JBank")" asp-area="" asp-controller="JBank" asp-action="Index">
                                Bank
                            </a>
                        </li>
                    </ul>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link  text-truncate collapsed py-1 ml-3
                @Html.ActiveClass("JAgama")
                @Html.ActiveClass("JBangsa")" href="#submenuJadualsub3" data-toggle="collapse" data-target="#submenuJadualsub3"><span>Pendaftaran</span></a>
                <div class="collapse" id="submenuJadualsub3" aria-expanded="false">
                    <ul class="flex-column nav pl-4">
                        <li class="nav-item">
                            <a class="nav-link p-1 text-truncate pl-4 @Html.ActiveSideBarClass("JAgama")" asp-area="" asp-controller="JAgama" asp-action="Index">
                                Agama
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link p-1 text-truncate pl-4 @Html.ActiveSideBarClass("JBangsa")" asp-area="" asp-controller="JBangsa" asp-action="Index">
                                Bangsa
                            </a>
                        </li>
                    </ul>
                </div>
            </li>

            <li class="nav-item"><a class="nav-link py-1 ml-3 @Html.ActiveSideBarClass("JSukan")" asp-area="" asp-controller="JSukan" asp-action="Index"><span>Sukan</span></a></li>
            <li class="nav-item"><a class="nav-link py-1 ml-3 @Html.ActiveSideBarClass("JTahapAktiviti")" asp-area="" asp-controller="JTahapAktiviti" asp-action="Index"><span>Tahap Aktiviti</span></a></li>
            <li class="nav-item"><a class="nav-link py-1 ml-3 @Html.ActiveSideBarClass("JNegeri")" asp-area="" asp-controller="JNegeri" asp-action="Index"><span>Negeri</span></a></li>
        
             <li class="nav-item">
                <a class="nav-link  text-truncate collapsed py-1 ml-3
                @Html.ActiveClass("JSuTarafJawatan")
                @Html.ActiveClass("JSuGredGaji")
                @Html.ActiveClass("JSuKodGaji")
                @Html.ActiveClass("JSuPCB")
                @Html.ActiveClass("JSuKWSP") " href="#submenuJadualsub4" data-toggle="collapse" data-target="#submenuJadualsub4"><span>Sumber Manusia</span></a>
                <div class="collapse" id="submenuJadualsub4" aria-expanded="false">
                    <ul class="flex-column nav pl-4">
                        <li class="nav-item">
                            <a class="nav-link p-1 text-truncate pl-4 @Html.ActiveSideBarClass("JSuTarafJawatan")" asp-area="" asp-controller="JSuTarafJawatan" asp-action="Index">
                                Taraf Jawatan
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link p-1 text-truncate pl-4 @Html.ActiveSideBarClass("JSuGredGaji")" asp-area="" asp-controller="JSuGredGaji" asp-action="Index">
                                Gred Gaji
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link p-1 text-truncate pl-4 @Html.ActiveSideBarClass("JSuKodGaji")" asp-area="" asp-controller="JSuKodGaji" asp-action="Index">
                                Kod Gaji
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link p-1 text-truncate pl-4 @Html.ActiveSideBarClass("JSuPCB")" asp-area="" asp-controller="JSuPCB" asp-action="Index">
                                PCB
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link p-1 text-truncate pl-4 @Html.ActiveSideBarClass("JSuKWSP")" asp-area="" asp-controller="JSuKWSP" asp-action="Index">
                                KWSP
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
</li>

           

Views/Shared/_LejarPartialNavbar.cshtml
@*<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Lejar
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <a class="dropdown-item" asp-area="" asp-controller="AkCarta" asp-action="Index">Carta Akaun</a>
        <a class="dropdown-item" asp-area="" asp-controller="AkAkaun" asp-action="Index">Lejar Am</a>
        <a class="dropdown-item" asp-area="" asp-controller="AbBukuVot" asp-action="Index">Buku Vot</a>
    </div>
</li>*@

<li class="nav-item">
    <a class="nav-link collapsed text-truncate
    @Html.ActiveClass("AkCarta")
    @Html.ActiveClass("AkAkaun")
    @Html.ActiveClass("AbBukuVot")" href="#submenuLejar" data-toggle="collapse" data-target="#submenuLejar"><i class="fa fa-book pr-2"></i><span class="pl-1">Lejar</span></a>
    <div class="collapse" id="submenuLejar" aria-expanded="false">
        <ul class="flex-column pl-2 nav">
            <li class="nav-item"><a class="nav-link py-1 ml-3 @Html.ActiveSideBarClass("AkCarta")" asp-controller="AkCarta" asp-action="Index"><span>Carta Akaun</span></a></li>
            <li class="nav-item"><a class="nav-link py-1 ml-3 @Html.ActiveSideBarClass("AkAkaun")" asp-area="" asp-controller="AkAkaun" asp-action="Index"><span>Lejar Am</span></a></li>
            <li class="nav-item"><a class="nav-link py-1 ml-3 @Html.ActiveSideBarClass("AbBukuVot")" asp-area="" asp-controller="AbBukuVot" asp-action="Index"><span>Buku Vot</span></a></li>
        </ul>
    </div>
</li>

Views/Shared/_Log_In_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <title>@ViewData["Title"] - SUMBER</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/util.css" />
    <link href="~/lib/animate.css/animate.min.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body class="gradient-form">
    @RenderBody()
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <title>@ViewData["Title"] - SUMBER</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/login.min.css" />
    <link rel="stylesheet" href="~/css/util.min.css" />
    <link href="~/lib/animate.css/animate.min.css" rel="stylesheet" />
</head>
<body style="font-size: 12px;">
    @RenderBody()
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_LoginPartialNavbar.cshtml
@{ 
    var user = UserManager.GetUserAsync(User);
    var namaUser = _context.applicationUsers.FirstOrDefault(x => x.Email == user.Result.Email);

}

<div class="nav-item dropdown">
    <button class="btn btn-block"><i class="fa fa-user-cog"></i></button>
    <div class=" dropdown-content">
        <a class="btn dropdown-item" asp-area="" asp-controller="Profile" asp-action="ChangePassword">Tukar Kata Laluan</a>
        <form id="logOutForm" method="post" class="form-inline" asp-controller="Account" asp-action="LogOff">
            <button type="submit" class="btn dropdown-item">Log Keluar</button>
        </form>
    </div>
    
</div>
            

@*<div class="dropdown">
    <span><i class="fa fa-user"></i></span>
    <div class="dropdown-content">
        <ul class="navbar-nav">
            @if (SignInManager.IsSignedIn(User))
            {
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" aria-expanded="false"><i class="fas fa-angle-down"></i> </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" asp-area="" asp-controller="Profile" asp-action="ChangePassword">Tukar Kata Laluan</a>
                        <form id="logOutForm" method="post" class="form-inline" asp-controller="Account" asp-action="LogOff">
                            <button type="submit" class="btn dropdown-item">Log Keluar</button>
                        </form>
                    </div>
                </li>
            }
            else
            {
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
                </li>
            }


        </ul>
    </div>
</div>*@
    @*<ul class="navbar-nav">
        @if (SignInManager.IsSignedIn(User))
        {
            <li class="nav-item dropdown">
                <a class="nav-link" href="#" aria-haspopup="true" aria-expanded="false"><i class="fas fa-angle-down"></i> </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" asp-area="" asp-controller="Profile" asp-action="ChangePassword">Tukar Kata Laluan</a>
                    <form id="logOutForm" method="post" class="form-inline" asp-controller="Account" asp-action="LogOff">
                        <button type="submit" class="btn dropdown-item">Log Keluar</button>
                    </form>
                </div>
            </li>
        }
        else
        {
            <li class="nav-item">
                <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
            </li>
        }


    </ul>*@

Views/Shared/_Notifications.cshtml
@if (TempData[SD.Success] != null)
{
    <script type="text/javascript">
        toastr.success('@TempData[SD.Success]');
        toastr.options.timeOut = 5000;
    </script>
}
@if (TempData[SD.Error] != null)
{
    <script type="text/javascript">
        toastr.error('@TempData[SD.Error]');
        toastr.options.timeOut = 5000;
    </script>
}

@if (TempData[SD.Warning] != null)
{
    <script type="text/javascript">
        toastr.warning('@TempData[SD.Warning]');
        toastr.options.timeOut = 5000;
    </script>
}

@if (TempData[SD.Info] != null)
{
    <script type="text/javascript">
        toastr.info('@TempData[SD.Info]');
        toastr.options.timeOut = 5000;
    </script>
}

Views/Shared/_SistemPartialNavbar.cshtml
@*<li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Sistem
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <a class="dropdown-item" asp-area="" asp-controller="User" asp-action="Index">Maklumat Pengguna</a>
        <a class="dropdown-item" asp-area="" asp-controller="Roles" asp-action="Index">Maklumat Tahap Pengguna</a>
        <a class="dropdown-item" asp-area="" asp-controller="AppLog" asp-action="Index">Log Transaksi Pengguna</a>
    </div>
</li>*@
<li class="nav-item">
    <a class="nav-link collapsed text-truncate 
    @Html.ActiveClass("User") 
    @Html.ActiveClass("Roles") 
    @Html.ActiveClass("AppLog") 
    @Html.ActiveClass("SiAppInfo")" 
    href="#submenuSistem" data-toggle="collapse" data-target="#submenuSistem"><i class="fa fa-cubes pr-2"></i><span class="pl-1">Sistem</span></a>
    <div class="collapse" id="submenuSistem" aria-expanded="false">
        <ul class="flex-column pl-2 nav">
            <li class="nav-item"><a class="nav-link py-1 ml-3 @Html.ActiveSideBarClass("User")" asp-controller="User" asp-action="Index"><span>Maklumat Pengguna</span></a></li>
            <li class="nav-item"><a class="nav-link py-1 ml-3 @Html.ActiveSideBarClass("Roles")" asp-area="" asp-controller="Roles" asp-action="Index"><span>Maklumat Tahap Pengguna</span></a></li>
            <li class="nav-item"><a class="nav-link py-1 ml-3 @Html.ActiveSideBarClass("AppLog")" asp-area="" asp-controller="AppLog" asp-action="Index"><span>Log Transaksi Pengguna</span></a></li>
            <li class="nav-item"><a class="nav-link py-1 ml-3 @Html.ActiveSideBarClass("SiAppInfo")" asp-area="" asp-controller="SiAppInfo" asp-action="Index"><span>Info Syarikat</span></a></li>
        </ul>
    </div>
</li>