Models/Modules/JBahagian.cs
using SUMBER.Models.Helper;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SUMBER.Models.Modules
{
    public class JBahagian : AppLogHelper, ISoftDelete
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Kod Diperlukan")]
        public string Kod { get; set; }
        [Required(ErrorMessage = "Perihal Diperlukan")]
        public string Perihal { get; set; }
        public JKW JKW { get; set; }
        [DisplayName("Kumpulan Wang")]
        [Required(ErrorMessage = "Kumpulan Wang Diperlukan")]
        public int JKWId { get; set; }
        public JPTJ JPTJ { get; set; }
        [DisplayName("PTJ")]
        public int? JPTJId { get; set; }
        public int FlHapus { get; set; }
        public DateTime? TarHapus { get; set; }

        public ICollection<AbWaran> AbWaran { get; set; }
        public ICollection<AbWaran1> AbWaran1 { get; set; }
        public ICollection<AbBukuVot> abBukuVot { get; set; }
        public ICollection<AkAkaun> AkAkaun { get; set; }
        public ICollection<AkBelian> AkBelian { get; set; }
        public ICollection<AkJurnal> AkJurnal { get; set; }
        public ICollection<AkNotaMinta> AkNotaMinta { get; set; }
        public ICollection<AkPO> AkPO { get; set; }
        public ICollection<AkInden> AkInden { get; set; }
        public ICollection<AkPOLaras> AkPOLaras { get; set; }
        public ICollection<AkPV> AkPV { get; set; }
        public ICollection<AkTerima> AkTerima { get; set; }
        public ICollection<AkTunaiLejar> AkTunaiLejar { get; set; }
        public ICollection<AkTunaiRuncit> AkTunaiRuncit { get; set; }
        public ICollection<SpPendahuluanPelbagai> SpPendahuluanPelbagai { get; set; }
        public ICollection<AkBank> AkBank { get; set; }
        public ICollection<SuProfil> SuProfil { get; set; }
        public ICollection<AkInvois> AkInvois { get; set; }
        public ICollection<AkPenyataPemungut1> AkPenyataPemungut1 { get; set; }
    }
}

Controllers/JBahagianController.cs
 using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SUMBER.Data;
using SUMBER.Models.Modules;
using SUMBER.Models.Modules.IRepository;

namespace SUMBER.Controllers
{
    [Authorize(Roles = "SuperAdmin,Supervisor")]
    public class JBahagianController : Controller
    {
        public const string modul = "JD002";
        public const string namamodul = "Jadual Bahagian";

        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IRepository<JBahagian, int, string> _jBahagianRepo;
        private readonly AppLogIRepository<AppLog, int> _appLog;

        public JBahagianController(ApplicationDbContext context,
            UserManager<IdentityUser> userManager,
            IRepository<JBahagian, int, string> jBahagianRepo,
            AppLogIRepository<AppLog, int> appLog)
        {
            _context = context;
            _userManager = userManager;
            _jBahagianRepo = jBahagianRepo;
            _appLog = appLog;
        }

        private async Task AddLogAsync(
            string operasi,
            string nota,
            string rujukan,
            int idRujukan,
            decimal jumlah,
            int? pekerjaId)
        {
            var user = await _userManager.GetUserAsync(User);
            AppLog appLog = new AppLog();

            appLog.IdRujukan = idRujukan;
            appLog.UserId = user.UserName;
            appLog.NoRujukan = rujukan;
            appLog.LgNote = namamodul + " - " + nota;
            appLog.Jumlah = jumlah;
            appLog.SuPekerjaId = pekerjaId;

            await _appLog.Insert(appLog, modul, operasi);
        }
        // GET: JBahagian
        public async Task<IActionResult> Index()
        {
            var obj = await _jBahagianRepo.GetAll();

            if (User.IsInRole("SuperAdmin"))
            {
                obj = await _jBahagianRepo.GetAllIncludeDeletedItems();
            }
            return View(obj);
        }

        // GET: JBahagian/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jBahagian = await _jBahagianRepo.GetById((int)id);

            if (jBahagian == null)
            {
                return NotFound();
            }

            return View(jBahagian);
        }

        // GET: JBahagian/Create
        public IActionResult Create()
        {
            // get latest no rujukan running number  
            var kw = _context.JKW.FirstOrDefault(x => x.Kod == "100");

            var kumpulanWang = kw.Kod;
            string prefix = kumpulanWang;
            int x = 1;
            string noRujukan = prefix + "00";

            var LatestNoRujukan = _context.JBahagian
                        .IgnoreQueryFilters()
                        .Where(x=> x.JKW.Kod == kw.Kod)
                        .Max(x => x.Kod);

            if (LatestNoRujukan == null)
            {
                noRujukan = string.Format("{0:" + prefix + "00}", x);
            }
            else
            {
                x = int.Parse(LatestNoRujukan.Substring(3));
                x++;
                noRujukan = string.Format("{0:" + prefix + "00}", x);
            }

            // get latest no rujukan running number end
            ViewBag.NoRujukan = noRujukan;

            List<JKW> list = _context.JKW.ToList();

            List<JPTJ> ptjlist = _context.JPTJ.ToList();

            ViewBag.JKw = list;
            ViewBag.JPtj = ptjlist;
            return View();
        }

        [HttpPost]
        public JsonResult JsonGetKod(int data)
        {
            try
            {
                var result = "";
                if (data == 0)
                {
                    result = "";
                }
                else
                {
                    // get latest no rujukan running number  
                    var kw = _context.JKW.FirstOrDefault(x => x.Id == data);

                    var kumpulanWang = kw.Kod;
                    string prefix = kumpulanWang;
                    int x = 1;
                    string noRujukan = prefix + "00";

                    var LatestNoRujukan = _context.JBahagian
                                .IgnoreQueryFilters()
                                .Where(x => x.JKW.Kod == kw.Kod)
                                .Max(x => x.Kod);

                    if (LatestNoRujukan == null)
                    {
                        noRujukan = string.Format("{0:" + prefix + "00}", x);
                    }
                    else
                    {
                        x = int.Parse(LatestNoRujukan.Substring(3));
                        x++;
                        noRujukan = string.Format("{0:" + prefix + "00}", x);
                    }

                    result = noRujukan;
                }
                return Json(new { result = "OK", record = result });
            }
            catch (Exception ex)
            {
                return Json(new { result = "Error", message = ex.Message });
            }
        }

        // POST: JBahagian/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(JBahagian jBahagian, int JKWId)
        {
            JBahagian m = new JBahagian();
            var user = await _userManager.GetUserAsync(User);
            int? pekerjaId = _context.applicationUsers.Where(b => b.Id == user.Id).FirstOrDefault().SuPekerjaId;

            var username = User.FindFirstValue(ClaimTypes.Name).Substring(0, 15);

            // get latest no rujukan running number  
            var kw = _context.JKW.FirstOrDefault(x => x.Id == JKWId);

            var kumpulanWang = kw.Kod;
            string prefix = kumpulanWang;
            int x = 1;
            string noRujukan = prefix + "00";

            var LatestNoRujukan = _context.JBahagian
                        .IgnoreQueryFilters()
                        .Where(x => x.JKW.Kod == kw.Kod)
                        .Max(x => x.Kod);

            if (LatestNoRujukan == null)
            {
                noRujukan = string.Format("{0:" + prefix + "00}", x);
            }
            else
            {
                x = int.Parse(LatestNoRujukan.Substring(3));
                x++;
                noRujukan = string.Format("{0:" + prefix + "00}", x);
            }

            if (jBahagian != null && JKWId != 0)
            {
                
                if (ModelState.IsValid)
                {
                    m.JKWId = JKWId;
                    m.JPTJId = jBahagian.JPTJId;
                    m.Kod = noRujukan;
                    m.Perihal = jBahagian.Perihal?.ToUpper() ?? null;
                    m.UserId = user.UserName;
                    m.TarMasuk = DateTime.Now;
                    m.SuPekerjaMasukId = pekerjaId;

                    _context.Add(m);
                    await AddLogAsync("Tambah", m.Kod + " - " + m.Perihal,m.Kod,0, 0, pekerjaId);
                    await _context.SaveChangesAsync();
                    TempData[SD.Success] = "Data berjaya ditambah..!";
                    return RedirectToAction(nameof(Index));
                }
            }

            List<JKW> list = _context.JKW.ToList();
            ViewBag.NoRujukan = noRujukan;
            ViewBag.JKw = list; 
            return View(jBahagian);
        }

        // GET: JBahagian/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jBahagian = await _context.JBahagian.FindAsync(id);
            if (jBahagian == null)
            {
                return NotFound();
            }
            List<JKW> list = _context.JKW.ToList();
            List<JPTJ> ptjList = _context.JPTJ.ToList();

            ViewBag.JKw = list;
            ViewBag.JPtj = ptjList;
            return View(jBahagian);
        }

        // POST: JBahagian/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,JBahagian jBahagian, int JKWId)
        {
            if (id != jBahagian.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var user = await _userManager.GetUserAsync(User);
                    int? pekerjaId = _context.applicationUsers.Where(b => b.Id == user.Id).FirstOrDefault().SuPekerjaId;

                    JBahagian jBahagianAsal = await _context.JBahagian.FindAsync(id);

                    // list of input that cannot be change
                    jBahagian.JKWId = jBahagianAsal.JKWId;
                    jBahagian.JPTJId = jBahagianAsal.JPTJId;
                    jBahagian.Kod = jBahagianAsal.Kod;
                    jBahagian.TarMasuk = jBahagianAsal.TarMasuk;
                    jBahagian.UserId = jBahagianAsal.UserId;
                    var perihalAsal = jBahagianAsal.Perihal;
                    // list of input that cannot be change end
                    _context.Entry(jBahagianAsal).State = EntityState.Detached;

                    jBahagian.Perihal = jBahagian.Perihal?.ToUpper()?? null;

Views/JBahagian/Create.cshtml
@model SUMBER.Models.Modules.JBahagian

@{
    ViewData["Title"] = "Bahagian - Tambah";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<partial name="_JSCreate" />

<div class="card box-shadow">
    <div class="card-body">
        <div class="row">
            <div class="col-8">
                <h5 class="text-uppercase text-success mb-0">Bahagian - Tambah</h5>
                <span class="ac-ref"><a asp-action="Index" class="text-secondary">Indeks</a> / Tambah</span>
            </div>
            <div class="col-4 text-right">
                <a asp-action="Index" class="text-secondary"><i class="fas fa-times fa-2x"></i></a>
            </div>
    
        </div>
        <hr class="mt-2"/>

        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="JKWId" class="control-label"></label>
                <select class="form-control form-control-sm text-uppercase" asp-for="JKWId" id="ddlKW">
                    @foreach (var s in ViewBag.JKW)
                    {
                        <option value="@s.Id">@s.Perihal </option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="JPTJId" class="control-label"></label>
                <select class="form-control form-control-sm text-uppercase" asp-for="JPTJId" id="ddlPTJ">
                    @foreach (var s in ViewBag.JPtj)
                    {
                        <option value="@s.Id">@s.Perihal </option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Kod" class="control-label"></label>
                <input asp-for="Kod" class="form-control form-control-sm" value="@ViewBag.NoRujukan" readonly id="txtNoRujukan"/>
                <span asp-validation-for="Kod" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Perihal" class="control-label"></label>
                <input asp-for="Perihal" class="form-control form-control-sm text-uppercase" />
                <span asp-validation-for="Perihal" class="text-danger"></span>
            </div>

            <div hidden>
                <div class="form-group">
                    <label asp-for="UserId" class="control-label"></label>
                    <input asp-for="UserId" class="form-control form-control-sm" />
                    <span asp-validation-for="UserId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TarMasuk" class="control-label"></label>
                    <input asp-for="TarMasuk" class="form-control form-control-sm" value="@DateTime.Now.ToString("s")"/>
                    <span asp-validation-for="TarMasuk" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="UserIdKemaskini" class="control-label"></label>
                    <input asp-for="UserIdKemaskini" class="form-control form-control-sm" />
                    <span asp-validation-for="UserIdKemaskini" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TarKemaskini" class="control-label"></label>
                    <input asp-for="TarKemaskini" class="form-control form-control-sm" value="@DateTime.Now.ToString("s")"/>
                    <span asp-validation-for="TarKemaskini" class="text-danger"></span>
                </div>
            </div>
            <hr />
            <div class="form-group">
                <input type="submit" value="Simpan" class="btn btn-primary btn-sm" />
                 <a asp-action="Index" class="btn ac-secondary btn-sm" style="width:auto">Batal</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/JBahagian/Delete.cshtml
@model SUMBER.Models.Modules.JBahagian

@{
    ViewData["Title"] = "Bahagian - Hapus";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="card box-shadow">
    <div class="card-body">
        <div class="row">
            <div class="col-8">
                <h5 class="text-uppercase text-danger mb-0">Bahagian - Hapus</h5>
                <span class="ac-ref"><a asp-action="Index" class="text-secondary">Indeks</a> / Hapus</span>
            </div>
            <div class="col-4 text-right">
                <a asp-action="Index" class="text-secondary"><i class="fas fa-times fa-2x"></i></a>
            </div>
    
        </div>
        <hr class="mt-2"/>
            <p class="text-danger">Anda pasti untuk menghapuskan maklumat berikut?</p>

            <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Kod)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Kod)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Perihal)
            </dt>
            <dd class="col-sm-10 text-uppercase">
                @Html.DisplayFor(model => model.Perihal)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.JKWId)
            </dt>
            <dd class="col-sm-10 text-uppercase">
                @Model.JKW.Kod - @Model.JKW.Perihal
            </dd>
        </dl>

        <hr />
        <div class="form-group">
             <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="Hapus" class="btn ac-danger btn-sm" /> 
                <a asp-action="Index" class="btn ac-secondary btn-sm" style="width:auto">Batal</a>
            </form>
            
        </div>
       
    </div>
</div>

Views/JBahagian/Details.cshtml
@model SUMBER.Models.Modules.JBahagian

@{
    ViewData["Title"] = "Bahagian - Papar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="card box-shadow">
    <div class="card-body">
        <div class="row">
            <div class="col-8">
                <h5 class="text-uppercase text-dark mb-0">Bahagian - Papar</h5>
                <span class="ac-ref"><a asp-action="Index" class="text-secondary">Indeks</a> / Papar</span>
            </div>
            <div class="col-4 text-right">
                <a asp-action="Index" class="text-secondary"><i class="fas fa-times fa-2x"></i></a>
            </div>
    
        </div>
        <hr class="mt-2"/>

        <dl class="row">
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Kod)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Kod)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Perihal)
            </dt>
            <dd class = "col-sm-10 text-uppercase">
                @Html.DisplayFor(model => model.Perihal)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.JKWId)
            </dt>
            <dd class = "col-sm-10 text-uppercase">
                @Model.JKW.Kod - @Model.JKW.Perihal
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.JPTJId)
            </dt>
            <dd class = "col-sm-10 text-uppercase">
                @Model.JPTJ.Kod - @Model.JPTJ.Perihal
            </dd>
        </dl>
        <hr />
        <div class="form-group">
            <a asp-action="Edit" asp-route-id="@Model.Id" class="btn ac-primary btn-sm">Ubah</a> 
            <a asp-action="Index" class="btn ac-secondary btn-sm" style="width:auto">Batal</a>
        </div>
    </div>
</div>

Views/JBahagian/Edit.cshtml
@model SUMBER.Models.Modules.JBahagian

@{
    ViewData["Title"] = "Bahagian - Ubah";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="card box-shadow">
    <div class="card-body">
        <div class="row">
            <div class="col-8">
                <h5 class="text-uppercase text-primary mb-0">Bahagian - Ubah</h5>
                <span class="ac-ref"><a asp-action="Index" class="text-secondary">Indeks</a> / <a asp-action="Details" asp-route-id="@Model.Id" class="text-secondary">Papar</a> / Ubah</span>
            </div>
            <div class="col-4 text-right">
                <a asp-action="Index" class="text-secondary"><i class="fas fa-times fa-2x"></i></a>
            </div>
    
        </div>
        <hr class="mt-2"/>

        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="JKWId" class="control-label"></label>
                <select class="form-control form-control-sm text-uppercase" asp-for="JKWId" id="ddlKW" disabled>
                    @foreach (var s in ViewBag.JKW)
                    {
                        <option value="@s.Id">@s.Perihal </option>
                    }
                </select>
            </div>

            <div class="form-group">
                <label asp-for="JPTJId" class="control-label"></label>
                <select class="form-control form-control-sm text-uppercase" asp-for="JPTJId" id="ddlPTJ" disabled>
                    @foreach (var s in ViewBag.JPtj)
                    {
                        <option value="@s.Id">@s.Perihal </option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Kod" class="control-label"></label>
                <input asp-for="Kod" class="form-control form-control-sm" readonly/>
                <span asp-validation-for="Kod" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Perihal" class="control-label"></label>
                <input asp-for="Perihal" class="form-control form-control-sm text-uppercase" />
                <span asp-validation-for="Perihal" class="text-danger"></span>
            </div>
            <div hidden>
                <div class="form-group">
                    <label asp-for="UserId" class="control-label"></label>
                    <input asp-for="UserId" class="form-control form-control-sm" />
                    <span asp-validation-for="UserId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TarMasuk" class="control-label"></label>
                    <input asp-for="TarMasuk" class="form-control form-control-sm" value="@DateTime.Now.ToString("s")" />
                    <span asp-validation-for="TarMasuk" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="UserIdKemaskini" class="control-label"></label>
                    <input asp-for="UserIdKemaskini" class="form-control form-control-sm" />
                    <span asp-validation-for="UserIdKemaskini" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TarKemaskini" class="control-label"></label>
                    <input asp-for="TarKemaskini" class="form-control form-control-sm" value="@DateTime.Now.ToString("s")" />
                    <span asp-validation-for="TarKemaskini" class="text-danger"></span>
                </div>
            </div>
            <hr />
            <div class="form-group">
                <input type="submit" value="Simpan" class="btn ac-primary btn-sm" />
                <a asp-action="Index" class="btn ac-secondary btn-sm" style="width:auto">Batal</a>
            </div>
        </form>

    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/JBahagian/Index.cshtml
@model IEnumerable<SUMBER.Models.Modules.JBahagian>

@{
    ViewData["Title"] = "Bahagian";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<partial name="_JSIndex" />

<div class="card box-shadow">
    <div class="card-body border">
        <div class="row">
            <div class="col-8">
                <h5 class="text-uppercase mb-0">Senarai Bahagian</h5>
                <span class="ac-ref">Indeks</span>
            </div>
            <div class="col-4 text-right">
                <a class="text-right btn ac-success" asp-action="Create">Tambah Baru</a>
            </div>
    
        </div>
        <hr class="mt-2"/>

        <div class="card mb-2">
            <div class="card-body pl-3 pb-2">
                <label class="form-control-plaintext" for="columnSearch">Carian : </label>
                <div class="form-actions no-color mb-2">
                    <div class="form-row">
                        <div class="col-sm-2 mb-2">
                            <select class="custom-select form-control-sm" id="columnSearch">
                                <option value="" selected>Semua</option>
                                <option value=".kod">Kod</option>
                                <option value=".nama">Nama</option>
                            </select>
                        </div>
                        <div class="col-sm-8 mb-2">
                            <input class="form-control form-control-sm" type="text" id="myInput" style="text-transform:uppercase" />
                        </div>
                        @*<div class="col-sm mb-2">
                                <button class="btn btn-warning btn-sm" id="batalCari" value="Batal Carian"><i class="fas fa-backspace"></i></button>
                            </div>*@
                    </div>
                </div>
            </div>
        </div>

        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap table-sm nowrap compact" width="100%">
                <thead>
                    <tr>
                        <th>Bil</th>
                        <th class="kod">
                            Kod
                        </th>
                        <th class="nama">
                            Perihal
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        var tabletype = item.FlHapus == 1 ? "table-danger" : null;
                        <tr class="@tabletype">
                            <td width="5%"></td>
                            <td width="5%">
                                @item.Kod
                            </td>
                            <td class="text-uppercase">
                                @item.Perihal
                            </td>
                            <td width="5%" class="text-center">
                                <div class="btn-group" role="group" aria-label="action">
                                    @if (item.FlHapus == 0)
                                    {
                                        <a asp-action="Details" asp-route-id="@item.Id"
                                           class="btn text-primary btn-sm bg-white" type="button"
                                           data-toggle="tooltip" data-placement="top"
                                           title="Ubah/Papar"><i class="fas fa-edit"></i></a>
                                        <a asp-action="Delete" asp-route-id="@item.Id"
                                           class="btn text-danger btn-sm bg-white" type="button"
                                           data-toggle="tooltip" data-placement="top"
                                           title="Hapus"><i class="fas fa-trash"></i></a>
                                    }
                                    else
                                    {
                                        if (User.IsInRole("Supervisor") || User.IsInRole("SuperAdmin"))
                                        {
                                            <a asp-action="Rollback" asp-route-id="@item.Id" class="btn text-info btn-sm bg-white" type="button" data-toggle="tooltip" data-placement="top" title="Rollback">
                                                <i class="fas fa-trash-restore"></i>
                                            </a>

                                        }
                                    }
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Views/JBahagian/_JSCreate.cshtml
<script type="text/javascript">
    // onchange no Rujukan
    $("body").on('change', "#ddlKW", function () {
        var kodKW = $("#ddlKW").val();
        if (kodKW != null) {
            JsonKod(kodKW);
        }

    });

    function JsonKod(id) {
        $.ajax({
            type: "POST",
            //url: "/AkPV/JsonGetKod",
            url: '@Url.Action("JsonGetKod", "JBahagian")',
            data: {data:id},
            dataType: "json",
            success: function (msg) {
                $("#txtNoRujukan").val(msg.record);
            },
            error: function (req, status, error) {
                alert(error);
            }
        });
    }
    // onchange no Rujukan end
</script>